/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : flexTimer1.h
**     Project     : DC2017_S32
**     Processor   : S32K144_100
**     Component   : ftm
**     Version     : Component SDK_S32K144_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K144_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-06-08, 10:50, # CodeGen: 2
**     Contents    :
**         FTM_DRV_Init                            - status_t FTM_DRV_Init(uint32_t instance,const ftm_user_config_t * info,...
**         FTM_DRV_Deinit                          - status_t FTM_DRV_Deinit(uint32_t instance);
**         FTM_DRV_InitCounter                     - status_t FTM_DRV_InitCounter(uint32_t instance,const ftm_timer_param_t *timer);
**         FTM_DRV_CounterStart                    - status_t FTM_DRV_CounterStart(uint32_t instance);
**         FTM_DRV_CounterStop                     - status_t FTM_DRV_CounterStop(uint32_t instance);
**         FTM_DRV_CounterRead                     - uint32_t FTM_DRV_CounterRead(uint32_t instance);
**         FTM_DRV_DeinitPwm                       - status_t FTM_DRV_DeinitPwm(uint32_t instance);
**         FTM_DRV_InitPwm                         - status_t FTM_DRV_InitPwm(uint32_t instance,const ftm_pwm_param_t * param);
**         FTM_DRV_UpdatePwmChannel                - status_t FTM_DRV_UpdatePwmChannel(uint32_t instance,uint8_t channel,...
**         FTM_DRV_UpdatePwmPeriod                 - status_t FTM_DRV_UpdatePwmPeriod(uint32_t instance,uint8_t channel,...
**         FTM_DRV_MaskOutputChannels              - status_t FTM_DRV_MaskOutputChannels(uint32_t instance, uint32_t channelsMask,...
**         FTM_DRV_SetInitialCounterValue          - status_t FTM_DRV_SetInitialCounterValue(uint32_t instance, uint16_t...
**         FTM_DRV_SetHalfCycleReloadPoint         - status_t FTM_DRV_SetHalfCycleReloadPoint(uint32_t instance, uint16_t...
**         FTM_DRV_SetSoftOutChnValue              - status_t FTM_DRV_SetSoftOutChnValue(uint32_t instance, uint8_t...
**         FTM_DRV_SetSoftwareOutputChannelControl - status_t FTM_DRV_SetSoftwareOutputChannelControl(uint32_t instance, uint8_t...
**         FTM_DRV_SetInvertingControl             - status_t FTM_DRV_SetInvertingControl(uint32_t instance, uint8_t...
**         FTM_DRV_SetModuloCounterValue           - status_t FTM_DRV_SetModuloCounterValue(uint32_t instance, uint16_t...
**         FTM_DRV_SetSync                         - status_t FTM_DRV_SetSync(uint32_t instance, const ftm_pwm_sync_t *param);
**         FTM_DRV_InitOutputCompare               - status_t FTM_DRV_InitOutputCompare(uint32_t instance,const...
**         FTM_DRV_DeinitOutputCompare             - status_t FTM_DRV_DeinitOutputCompare(uint32_t instance,const...
**         FTM_DRV_UpdateOutputCompareChannel      - status_t FTM_DRV_UpdateOutputCompareChannel(uint32_t instance,uint8_t...
**         FTM_DRV_InitInputCapture                - status_t FTM_DRV_InitInputCapture(uint32_t instance,const ftm_input_param_t *...
**         FTM_DRV_DeinitInputCapture              - status_t FTM_DRV_DeinitInputCapture(uint32_t instance,const ftm_input_param_t...
**         FTM_DRV_GetInputCaptureMeasurement      - uint16_t FTM_DRV_GetInputCaptureMeasurement(uint32_t instance,uint8_t channel);
**         FTM_DRV_StartNewSignalMeasurement       - status_t FTM_DRV_StartNewSignalMeasurement(uint32_t instance,uint8_t channel);
**         FTM_DRV_QuadDecodeStart                 - status_t FTM_DRV_QuadDecodeStart(uint32_t instance,const...
**         FTM_DRV_QuadDecodeStop                  - status_t FTM_DRV_QuadDecodeStop(uint32_t instance);
**         FTM_DRV_QuadGetState                    - ftm_quad_decoder_state_t FTM_DRV_QuadGetState(uint32_t instance);
**         FTM_DRV_GetFrequency                    - uint32_t FTM_DRV_GetFrequency(uint32_t instance);
**         FTM_DRV_ConvertFreqToPeriodTicks        - uint16_t FTM_DRV_ConvertFreqToPeriodTicks(uint32_t instance,uint32_t...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file flexTimer1.h
** @version 01.00
*/
/*!
**  @addtogroup flexTimer1_module flexTimer1 module documentation
**  @{
*/
#ifndef flexTimer1_H
#define flexTimer1_H

/* MODULE flexTimer1. */

/* Include inherited beans */
#include "clockMan1.h"
#include "ftm_driver.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define INST_FLEXTIMER1 0U


#endif
/* ifndef flexTimer1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/




extern ftm_timer_param_t flexTimer1_TimerConfig;

/* Global configuration of flexTimer1 */
extern ftm_user_config_t  flexTimer1_InitConfig;
