/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : osif1.h
**     Project     : DC2017_S32
**     Processor   : S32K144_100
**     Component   : osif
**     Version     : Component SDK_S32K144_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K144_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-06-08, 10:35, # CodeGen: 1
**     Contents    :
**         OSIF_TimeDelay       - void OSIF_TimeDelay(const uint32_t delay);
**         OSIF_MutexLock       - status_t OSIF_MutexLock(const mutex_t *const pMutex,const uint32_t timeout);
**         OSIF_MutexUnlock     - status_t OSIF_MutexUnlock(const mutex_t *const pMutex);
**         OSIF_MutexCreate     - status_t OSIF_MutexCreate(mutex_t *const pMutex);
**         OSIF_MutexDestroy    - status_t OSIF_MutexDestroy(const mutex_t *const pMutex);
**         OSIF_SemaWait        - status_t OSIF_SemaWait(semaphore_t *const pSem,const uint32_t timeout);
**         OSIF_SemaPost        - status_t OSIF_SemaPost(semaphore_t *const pSem);
**         OSIF_SemaCreate      - status_t OSIF_SemaCreate(semaphore_t *const pSem,const uint8_t initValue);
**         OSIF_SemaDestroy     - status_t OSIF_SemaDestroy(const semaphore_t *const pSem);
**         OSIF_GetMilliseconds - uint32_t OSIF_GetMilliseconds(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file osif1.h
** @version 01.00
*/
/*!
**  @addtogroup osif1_module osif1 module documentation
**  @{
*/
#ifndef osif1_H
#define osif1_H
/* MODULE osif1. */
/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
#include "osif.h"

/*! @brief Device instance number */


/* This file is generated automatically by OS Interface layer and is intentionally
    left empty */

#endif
/* ifndef osif1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
